select
    stg_intellisphere__patient.PatientID as record_id
    , NULL as redcap_repeat_instrument
    , NULL as redcap_repeat_instance
    , stg_intellisphere__patient.PatientName as name
    , stg_intellisphere__patient.DateOfBirth as date_of_birth
    , stg_intellisphere__patient.mrn as mrn
    , case 
        when stg_intellisphere__patient.gender = 'Male' then 1
        when stg_intellisphere__patient.gender = 'Female' then 2
        else NULL
        end as gender
    , case
        when stg_intellisphere__patient.race = 'American Indian or Alaska Native' then 1
        when stg_intellisphere__patient.race = 'Asian' then 2
        when stg_intellisphere__patient.race = 'Black or African American' then 3
        when stg_intellisphere__patient.race = 'Native Hawaiian or Other Pacific Islander' then 4
        when stg_intellisphere__patient.race = 'White' then 5
        when stg_intellisphere__patient.race = 'Multiple Categories Reported' then 6
        when stg_intellisphere__patient.race = 'Race Unknown' then 7
        else 7
        end as race_ethnicity
    , 2 as patient_information_complete
    , NULL as date_of_study
    , NULL as access
    , NULL as medical_history
    , NULL as diabetes
    , NULL as hypertension
    , NULL as hyperlidemia
    , NULL as smoking_history___1
    , NULL as smoking_history___2
    , NULL as smoking_history___3
    , NULL as smoking_history___4
    , NULL as diagnosis
    , NULL as systolic_1
    , NULL as diastolic_1
    , NULL as pulse
    , NULL as location
    , NULL as cpt_codes___1
    , NULL as cpt_codes___2
    , NULL as cpt_codes___3
    , NULL as cpt_codes___4
    , NULL as cpt_codes___5
    , NULL as cpt_codes___6
    , NULL as scanstcd___1
    , NULL as scanstcd___2
    , NULL as scanstcd___3
    , NULL as scanstcd___4
    , NULL as scanstcd___5
    , NULL as scanstcd___6
    , NULL as right_va
    , NULL as left_va
    , NULL as left_side_impression
    , NULL as basilar_artery_mv
    , NULL as basilar_artery_depth
    , NULL as basilar_artery_pi
    , NULL as right_mca_depth
    , NULL as right_mca_mv
    , NULL as right_mca_pi
    , NULL as distal_mca_depth
    , NULL as distal_mca_mv
    , NULL as distal_mca_pi
    , NULL as right_aca_depth
    , NULL as right_aca_mv
    , NULL as right_aca_pi
    , NULL as right_terminal_ica_depth
    , NULL as right_terminal_ica_mv
    , NULL as right_terminal_ica_pi
    , NULL as right_oa_pi
    , NULL as right_oa_mv
    , NULL as right_oa_forward_depth
    , NULL as right_ic_pi
    , NULL as right_ic_siphon_depth
    , NULL as right_ic_siphon_mv
    , NULL as right_va_depth
    , NULL as right_va_mv
    , NULL as right_va_pi
    , NULL as right_pca_depth
    , NULL as right_pca_mv
    , NULL as right_pca_pi
    , NULL as right_pca2_depth
    , NULL as right_pca2_mv
    , NULL as right_pca2_pi
    , NULL as left_mca_depth
    , NULL as left_mca_mv
    , NULL as left_mca_pi
    , NULL as left_mca2_mv
    , NULL as left_mca2_depth
    , NULL as left_mca2_pi
    , NULL as left_aca_depth
    , NULL as left_aca_mean_velocity
    , NULL as left_aca_pulsatitility_ind
    , NULL as left_terminal_ica_depth
    , NULL as left_terminal_ica_pi
    , NULL as left_terminal_mv
    , NULL as left_ic_siphon_depth
    , NULL as left_ic_siphon_mv
    , NULL as left_ic_siphon_pi
    , NULL as left_oa_forward_depth
    , NULL as left_oa_mv
    , NULL as left_oa_pi
    , NULL as left_pca_depth
    , NULL as left_pca_mv
    , NULL as left_pca_pi
    , NULL as left_pca2_depth
    , NULL as left_pca2_mv
    , NULL as left_pca2_pi
    , NULL as left_va_mv
    , NULL as left_va_depth
    , NULL as left_va_pi
    , NULL as other_studies
    , NULL as rcca_proximal_psv
    , NULL as right_cca_proximal_edv
    , NULL as rcca_prox_others
    , NULL as rcca_plaques
    , NULL as rcca_pro_sten
    , NULL as rcca_proximal_stent
    , NULL as rica_stent_p
    , NULL as rcca_instent_s
    , NULL as rcca_distal_psv
    , NULL as right_cca_distal_edv
    , NULL as rcca_dis_ot
    , NULL as rcca_distal_p
    , NULL as right_cca_distal_stenosis
    , NULL as rcca_d_ste
    , NULL as rica_d_stent_p
    , NULL as rccad_instent_s
    , NULL as rica_proximal_psv
    , NULL as rica_proximal_edv
    , NULL as rica_p_other
    , NULL as rica_pro_p
    , NULL as r_ica_proximal_stenosis
    , NULL as rica_proximal_ste
    , NULL as rica_p_stent_p
    , NULL as ricap_instent_s
    , NULL as rica_mid_segment_psv
    , NULL as right_ica_ms_edv
    , NULL as rica_ms_othe
    , NULL as rica_mid_p
    , NULL as r_ica_mid_stenosis
    , NULL as rica_mid_stent
    , NULL as rica_m_stent_p
    , NULL as ricam_instent_s
    , NULL as rica_distal_psv
    , NULL as right_ica_distal_edv
    , NULL as rica_dica_other
    , NULL as rica_distal_p
    , NULL as r_ica_d_sten
    , NULL as rica_dist_stent
    , NULL as rica_d_stent_p_4
    , NULL as ricad_instent_s
    , NULL as reca_distal_psv
    , NULL as right_eca_edv
    , NULL as right_eca_other
    , NULL as reca_distal_p
    , NULL as r_eca_sten
    , NULL as reca_distal_stent
    , NULL as reca_d_stent_p
    , NULL as recad_instent_s
    , NULL as right_vertebral_psv
    , NULL as right_vertebral_edv
    , NULL as rv_other
    , NULL as rvertebral_p
    , NULL as r_vet_sten
    , NULL as rvertebral_stent
    , NULL as rv_stent_p
    , NULL as rv_instent_s
    , NULL as lcca_proximal_psv
    , NULL as left_cca_proximal_edv
    , NULL as lcca_prox_others
    , NULL as lcca_plaques
    , NULL as lcca_pro_sten
    , NULL as lcca_proximal_stent
    , NULL as lica_stent_p
    , NULL as lcca_instent_s
    , NULL as lcca_distal_psv
    , NULL as left_cca_distal_edv
    , NULL as lcca_dis_ot
    , NULL as lcca_distal_p
    , NULL as left_cca_distal_stenosis
    , NULL as lcca_d_ste
    , NULL as lica_d_stent_p
    , NULL as lccad_instent_s
    , NULL as lica_proximal_psv
    , NULL as lica_proximal_edv
    , NULL as lica_p_other
    , NULL as lica_pro_p
    , NULL as l_ica_proximal_stenosis
    , NULL as lica_proximal_ste
    , NULL as lica_p_stent_p
    , NULL as licap_instent_s
    , NULL as lica_mid_segment_psv
    , NULL as left_ica_ms_edv
    , NULL as lica_ms_othe
    , NULL as lica_mid_p
    , NULL as l_ica_mid_stenosis
    , NULL as lica_mid_stent
    , NULL as lica_m_stent_p
    , NULL as licam_instent_s
    , NULL as lica_distal_psv
    , NULL as left_ica_distal_edv
    , NULL as lica_dica_other
    , NULL as lica_distal_p
    , NULL as l_ica_d_sten
    , NULL as lica_dist_stent
    , NULL as lica_d_stent_p_4
    , NULL as licad_instent_s
    , NULL as leca_distal_psv
    , NULL as left_eca_edv
    , NULL as left_eca_other
    , NULL as leca_distal_p
    , NULL as l_eca_sten
    , NULL as leca_distal_stent
    , NULL as leca_d_stent_p
    , NULL as lecad_instent_s
    , NULL as left_vertebral_psv
    , NULL as left_vertebral_edv
    , NULL as lv_other
    , NULL as lvertebral_p
    , NULL as l_vet_sten
    , NULL as lvertebral_stent
    , NULL as lv_stent_p
    , NULL as lv_instent_s
    , NULL as interpretation_summary
    , NULL as other_studies_7
    , NULL as baseline_time
    , NULL as baseline_time_2
    , NULL as st_co2_started
    , NULL as st_co2_started_2
    , NULL as nd_co2_started
    , NULL as nd_co2_started_2
    , NULL as st_post_co2
    , NULL as st_post_co2_2
    , NULL as nd_post_co2
    , NULL as nd_post_co2_2
    , NULL as left_distal_m1_psv
    , NULL as right_distal_m1_psv
    , NULL as left_distal_edv
    , NULL as right_distal_edv
    , NULL as left_distal_mean
    , NULL as right_distal_mean
    , NULL as left_distal_pi
    , NULL as right_distal_pi
    , NULL as co2_distal_pi
    , NULL as co2_distal_pi_r
    , NULL as co2_distal_pi_2
    , NULL as co2_distal_pi_r2
    , NULL as co2_distal_psv
    , NULL as co2_distal_psv_r
    , NULL as co2_distal_psv_2
    , NULL as co2_distal_psv_r2
    , NULL as co2_distal_edv
    , NULL as co2_distal_edv_r
    , NULL as co2_distal_edv_2
    , NULL as co2_distal_edv_r2
    , NULL as co2_distal_mean
    , NULL as co2_distal_mean_r
    , NULL as co2_distal_mean_2
    , NULL as co2_distal_mean_r2
    , NULL as post_1st_m1_psv
    , NULL as post_1st_m1_psv_r
    , NULL as post_1st_m1_edv
    , NULL as post_1st_m1_edv_r
    , NULL as post_1st_m1_pi
    , NULL as post_1st_m1_pi_r
    , NULL as post_1st_m1_mean
    , NULL as post_1st_m1_mean_r
    , NULL as post_2_m1_pi
    , NULL as post_2_m1_pi_r
    , NULL as post_2_m1_psv
    , NULL as post_2_m1_psv_r
    , NULL as post_2_m1_edv
    , NULL as post_2_m1_edv_r
    , NULL as post_2_m1_mean
    , NULL as post_2_m1_mean_r
    , NULL as impression
    , NULL as other_studies_3
    , NULL as artery_insonated_v2___1
    , NULL as artery_insonated_v2___2
    , NULL as artery_insonated_v2___3
    , NULL as no_of_hits_in_left_mca_v2
    , NULL as basilar_artery_hits_v2
    , NULL as no_of_hits_in_basilar_aret_v2
    , NULL as left_mca_hits_v2
    , NULL as hits_present_v2
    , NULL as no_of_hits_v2
    , NULL as sonographer_impression
    , NULL as other_studies_4
    , NULL as artery_insonated___1
    , NULL as artery_insonated___2
    , NULL as artery_insonated___3
    , NULL as hits_present
    , NULL as no_of_hits
    , NULL as left_mca_hits
    , NULL as no_of_hits_in_left_mca
    , NULL as basilar_artery_hits
    , NULL as no_of_hits_in_basilar_aret
    , NULL as impression2
    , NULL as other_studies_6
    , NULL as patient_background_information_complete
from
    {{ ref('stg_intellisphere__patient')}} 